language: java
jdk:
  - openjdk8
  - openjdk9
script:
  - ./mvnw clean install
  - ./mvnw -f examples/pom.xml clean verify -fae
deploy:
  provider: script
  script: "echo 'todo'"
  on:
    tags: true
